#! python
# PTdict.py - A python dictionary that contains info from the periodic table.

pt_dict = {'Ac': {'atomic mass': '227',
        'atomic number': '89',
        'electrons': '138',
        'group': '3',
        'name': 'Actinium',
        'period': '7',
        'type': 'Actinide'},
 'Ag': {'atomic mass': '107.868',
        'atomic number': '47',
        'electrons': '61',
        'group': '11',
        'name': 'Silver',
        'period': '5',
        'type': 'Transition Metal'},
 'Al': {'atomic mass': '26.982',
        'atomic number': '13',
        'electrons': '14',
        'group': '13',
        'name': 'Aluminum',
        'period': '3',
        'type': 'Metal'},
 'Am': {'atomic mass': '243',
        'atomic number': '95',
        'electrons': '148',
        'group': '',
        'name': 'Americium',
        'period': '7',
        'type': 'Actinide'},
 'Ar': {'atomic mass': '39.948',
        'atomic number': '18',
        'electrons': '22',
        'group': '18',
        'name': 'Argon',
        'period': '3',
        'type': 'Noble Gas'},
 'As': {'atomic mass': '74.922',
        'atomic number': '33',
        'electrons': '42',
        'group': '15',
        'name': 'Arsenic',
        'period': '4',
        'type': 'Metalloid'},
 'At': {'atomic mass': '210',
        'atomic number': '85',
        'electrons': '125',
        'group': '17',
        'name': 'Astatine',
        'period': '6',
        'type': 'Noble Gas'},
 'Au': {'atomic mass': '196.967',
        'atomic number': '79',
        'electrons': '118',
        'group': '11',
        'name': 'Gold',
        'period': '6',
        'type': 'Transition Metal'},
 'B': {'atomic mass': '10.811',
       'atomic number': '5',
       'electrons': '6',
       'group': '13',
       'name': 'Boron',
       'period': '2',
       'type': 'Metalloid'},
 'Ba': {'atomic mass': '137.327',
        'atomic number': '56',
        'electrons': '81',
        'group': '2',
        'name': 'Barium',
        'period': '6',
        'type': 'Alkaline Earth Metal'},
 'Be': {'atomic mass': '9.012',
        'atomic number': '4',
        'electrons': '5',
        'group': '2',
        'name': 'Beryllium',
        'period': '2',
        'type': 'Alkaline Earth Metal'},
 'Bh': {'atomic mass': '264',
        'atomic number': '107',
        'electrons': '157',
        'group': '7',
        'name': 'Bohrium',
        'period': '7',
        'type': 'Transactinide'},
 'Bi': {'atomic mass': '208.98',
        'atomic number': '83',
        'electrons': '126',
        'group': '15',
        'name': 'Bismuth',
        'period': '6',
        'type': 'Metal'},
 'Bk': {'atomic mass': '247',
        'atomic number': '97',
        'electrons': '150',
        'group': '',
        'name': 'Berkelium',
        'period': '7',
        'type': 'Actinide'},
 'Br': {'atomic mass': '79.904',
        'atomic number': '35',
        'electrons': '45',
        'group': '17',
        'name': 'Bromine',
        'period': '4',
        'type': 'Halogen'},
 'C': {'atomic mass': '12.011',
       'atomic number': '6',
       'electrons': '6',
       'group': '14',
       'name': 'Carbon',
       'period': '2',
       'type': 'Nonmetal'},
 'Ca': {'atomic mass': '40.078',
        'atomic number': '20',
        'electrons': '20',
        'group': '2',
        'name': 'Calcium',
        'period': '4',
        'type': 'Alkaline Earth Metal'},
 'Cd': {'atomic mass': '112.411',
        'atomic number': '48',
        'electrons': '64',
        'group': '12',
        'name': 'Cadmium',
        'period': '5',
        'type': 'Transition Metal'},
 'Ce': {'atomic mass': '140.116',
        'atomic number': '58',
        'electrons': '82',
        'group': '',
        'name': 'Cerium',
        'period': '6',
        'type': 'Lanthanide'},
 'Cf': {'atomic mass': '251',
        'atomic number': '98',
        'electrons': '153',
        'group': '',
        'name': 'Californium',
        'period': '7',
        'type': 'Actinide'},
 'Cl': {'atomic mass': '35.453',
        'atomic number': '17',
        'electrons': '18',
        'group': '17',
        'name': 'Chlorine',
        'period': '3',
        'type': 'Halogen'},
 'Cm': {'atomic mass': '247',
        'atomic number': '96',
        'electrons': '151',
        'group': '',
        'name': 'Curium',
        'period': '7',
        'type': 'Actinide'},
 'Cn ': {'atomic mass': '285',
         'atomic number': '112',
         'electrons': '173',
         'group': '12',
         'name': 'Copernicium ',
         'period': '7',
         'type': 'Transactinide'},
 'Co': {'atomic mass': '58.933',
        'atomic number': '27',
        'electrons': '32',
        'group': '9',
        'name': 'Cobalt',
        'period': '4',
        'type': 'Transition Metal'},
 'Cr': {'atomic mass': '51.996',
        'atomic number': '24',
        'electrons': '28',
        'group': '6',
        'name': 'Chromium',
        'period': '4',
        'type': 'Transition Metal'},
 'Cs': {'atomic mass': '132.905',
        'atomic number': '55',
        'electrons': '78',
        'group': '1',
        'name': 'Cesium',
        'period': '6',
        'type': 'Alkali Metal'},
 'Cu': {'atomic mass': '63.546',
        'atomic number': '29',
        'electrons': '35',
        'group': '11',
        'name': 'Copper',
        'period': '4',
        'type': 'Transition Metal'},
 'Db': {'atomic mass': '262',
        'atomic number': '105',
        'electrons': '157',
        'group': '5',
        'name': 'Dubnium',
        'period': '7',
        'type': 'Transactinide'},
 'Ds ': {'atomic mass': '271',
         'atomic number': '110',
         'electrons': '161',
         'group': '10',
         'name': 'Darmstadtium ',
         'period': '7',
         'type': 'Transactinide'},
 'Dy': {'atomic mass': '162.5',
        'atomic number': '66',
        'electrons': '97',
        'group': '',
        'name': 'Dysprosium',
        'period': '6',
        'type': 'Lanthanide'},
 'Er': {'atomic mass': '167.259',
        'atomic number': '68',
        'electrons': '99',
        'group': '',
        'name': 'Erbium',
        'period': '6',
        'type': 'Lanthanide'},
 'Es': {'atomic mass': '252',
        'atomic number': '99',
        'electrons': '153',
        'group': '',
        'name': 'Einsteinium',
        'period': '7',
        'type': 'Actinide'},
 'Eu': {'atomic mass': '151.964',
        'atomic number': '63',
        'electrons': '89',
        'group': '',
        'name': 'Europium',
        'period': '6',
        'type': 'Lanthanide'},
 'F': {'atomic mass': '18.998',
       'atomic number': '9',
       'electrons': '10',
       'group': '17',
       'name': 'Fluorine',
       'period': '2',
       'type': 'Halogen'},
 'Fe': {'atomic mass': '55.845',
        'atomic number': '26',
        'electrons': '30',
        'group': '8',
        'name': 'Iron',
        'period': '4',
        'type': 'Transition Metal'},
 'Fl': {'atomic mass': '289',
        'atomic number': '114',
        'electrons': '175',
        'group': '14',
        'name': 'Flerovium',
        'period': '7',
        'type': 'Transactinide'},
 'Fm': {'atomic mass': '257',
        'atomic number': '100',
        'electrons': '157',
        'group': '',
        'name': 'Fermium',
        'period': '7',
        'type': 'Actinide'},
 'Fr': {'atomic mass': '223',
        'atomic number': '87',
        'electrons': '136',
        'group': '1',
        'name': 'Francium',
        'period': '7',
        'type': 'Alkaline Earth Metal'},
 'Ga': {'atomic mass': '69.723',
        'atomic number': '31',
        'electrons': '39',
        'group': '13',
        'name': 'Gallium',
        'period': '4',
        'type': 'Metal'},
 'Gd': {'atomic mass': '157.25',
        'atomic number': '64',
        'electrons': '93',
        'group': '',
        'name': 'Gadolinium',
        'period': '6',
        'type': 'Lanthanide'},
 'Ge': {'atomic mass': '72.64',
        'atomic number': '32',
        'electrons': '41',
        'group': '14',
        'name': 'Germanium',
        'period': '4',
        'type': 'Metalloid'},
 'H': {'atomic mass': '1.007',
       'atomic number': '1',
       'electrons': '0',
       'group': '1',
       'name': 'Hydrogen',
       'period': '1',
       'type': 'Nonmetal'},
 'He': {'atomic mass': '4.002',
        'atomic number': '2',
        'electrons': '2',
        'group': '18',
        'name': 'Helium',
        'period': '1',
        'type': 'Noble Gas'},
 'Hf': {'atomic mass': '178.49',
        'atomic number': '72',
        'electrons': '106',
        'group': '4',
        'name': 'Hafnium',
        'period': '6',
        'type': 'Transition Metal'},
 'Hg': {'atomic mass': '200.59',
        'atomic number': '80',
        'electrons': '121',
        'group': '12',
        'name': 'Mercury',
        'period': '6',
        'type': 'Transition Metal'},
 'Ho': {'atomic mass': '164.93',
        'atomic number': '67',
        'electrons': '98',
        'group': '',
        'name': 'Holmium',
        'period': '6',
        'type': 'Lanthanide'},
 'Hs': {'atomic mass': '267',
        'atomic number': '108',
        'electrons': '159',
        'group': '8',
        'name': 'Hassium',
        'period': '7',
        'type': 'Transactinide'},
 'I': {'atomic mass': '126.904',
       'atomic number': '53',
       'electrons': '74',
       'group': '17',
       'name': 'Iodine',
       'period': '5',
       'type': 'Halogen'},
 'In': {'atomic mass': '114.818',
        'atomic number': '49',
        'electrons': '66',
        'group': '13',
        'name': 'Indium',
        'period': '5',
        'type': 'Metal'},
 'Ir': {'atomic mass': '192.217',
        'atomic number': '77',
        'electrons': '115',
        'group': '9',
        'name': 'Iridium',
        'period': '6',
        'type': 'Transition Metal'},
 'K': {'atomic mass': '39.098',
       'atomic number': '19',
       'electrons': '20',
       'group': '1',
       'name': 'Potassium',
       'period': '4',
       'type': 'Alkali Metal'},
 'Kr': {'atomic mass': '83.798',
        'atomic number': '36',
        'electrons': '48',
        'group': '18',
        'name': 'Krypton',
        'period': '4',
        'type': 'Noble Gas'},
 'La': {'atomic mass': '138.905',
        'atomic number': '57',
        'electrons': '82',
        'group': '3',
        'name': 'Lanthanum',
        'period': '6',
        'type': 'Lanthanide'},
 'Li': {'atomic mass': '6.941',
        'atomic number': '3',
        'electrons': '4',
        'group': '1',
        'name': 'Lithium',
        'period': '2',
        'type': 'Alkali Metal'},
 'Lr': {'atomic mass': '262',
        'atomic number': '103',
        'electrons': '159',
        'group': '',
        'name': 'Lawrencium',
        'period': '7',
        'type': 'Actinide'},
 'Lu': {'atomic mass': '174.967',
        'atomic number': '71',
        'electrons': '104',
        'group': '',
        'name': 'Lutetium',
        'period': '6',
        'type': 'Lanthanide'},
 'Lv': {'atomic mass': '292',
        'atomic number': '116',
        'electrons': '176',
        'group': '16',
        'name': 'Livermorium',
        'period': '7',
        'type': 'Transactinide'},
 'Mc': {'atomic mass': '288',
        'atomic number': '115',
        'electrons': '173',
        'group': '15',
        'name': 'Moscovium',
        'period': '7',
        'type': ''},
 'Md': {'atomic mass': '258',
        'atomic number': '101',
        'electrons': '157',
        'group': '',
        'name': 'Mendelevium',
        'period': '7',
        'type': 'Actinide'},
 'Mg': {'atomic mass': '24.305',
        'atomic number': '12',
        'electrons': '12',
        'group': '2',
        'name': 'Magnesium',
        'period': '3',
        'type': 'Alkaline Earth Metal'},
 'Mn': {'atomic mass': '54.938',
        'atomic number': '25',
        'electrons': '30',
        'group': '7',
        'name': 'Manganese',
        'period': '4',
        'type': 'Transition Metal'},
 'Mo': {'atomic mass': '95.96',
        'atomic number': '42',
        'electrons': '54',
        'group': '6',
        'name': 'Molybdenum',
        'period': '5',
        'type': 'Transition Metal'},
 'Mt': {'atomic mass': '268',
        'atomic number': '109',
        'electrons': '159',
        'group': '9',
        'name': 'Meitnerium',
        'period': '7',
        'type': 'Transactinide'},
 'N': {'atomic mass': '14.007',
       'atomic number': '7',
       'electrons': '7',
       'group': '15',
       'name': 'Nitrogen',
       'period': '2',
       'type': 'Nonmetal'},
 'Na': {'atomic mass': '22.99',
        'atomic number': '11',
        'electrons': '12',
        'group': '1',
        'name': 'Sodium',
        'period': '3',
        'type': 'Alkali Metal'},
 'Nb': {'atomic mass': '92.906',
        'atomic number': '41',
        'electrons': '52',
        'group': '5',
        'name': 'Niobium',
        'period': '5',
        'type': 'Transition Metal'},
 'Nd': {'atomic mass': '144.242',
        'atomic number': '60',
        'electrons': '84',
        'group': '',
        'name': 'Neodymium',
        'period': '6',
        'type': 'Lanthanide'},
 'Ne': {'atomic mass': '20.18',
        'atomic number': '10',
        'electrons': '10',
        'group': '18',
        'name': 'Neon',
        'period': '2',
        'type': 'Noble Gas'},
 'Nh': {'atomic mass': '284',
        'atomic number': '113',
        'electrons': '171',
        'group': '13',
        'name': 'Nihonium',
        'period': '7',
        'type': ''},
 'Ni': {'atomic mass': '58.693',
        'atomic number': '28',
        'electrons': '31',
        'group': '10',
        'name': 'Nickel',
        'period': '4',
        'type': 'Transition Metal'},
 'No': {'atomic mass': '259',
        'atomic number': '102',
        'electrons': '157',
        'group': '',
        'name': 'Nobelium',
        'period': '7',
        'type': 'Actinide'},
 'Np': {'atomic mass': '237',
        'atomic number': '93',
        'electrons': '144',
        'group': '',
        'name': 'Neptunium',
        'period': '7',
        'type': 'Actinide'},
 'O': {'atomic mass': '15.999',
       'atomic number': '8',
       'electrons': '8',
       'group': '16',
       'name': 'Oxygen',
       'period': '2',
       'type': 'Nonmetal'},
 'Og': {'atomic mass': '294',
        'atomic number': '118',
        'electrons': '176',
        'group': '18',
        'name': 'Oganesson',
        'period': '7',
        'type': 'Noble Gas'},
 'Os': {'atomic mass': '190.23',
        'atomic number': '76',
        'electrons': '114',
        'group': '8',
        'name': 'Osmium',
        'period': '6',
        'type': 'Transition Metal'},
 'P': {'atomic mass': '30.974',
       'atomic number': '15',
       'electrons': '16',
       'group': '15',
       'name': 'Phosphorus',
       'period': '3',
       'type': 'Nonmetal'},
 'Pa': {'atomic mass': '231.036',
        'atomic number': '91',
        'electrons': '140',
        'group': '',
        'name': 'Protactinium',
        'period': '7',
        'type': 'Actinide'},
 'Pb': {'atomic mass': '207.2',
        'atomic number': '82',
        'electrons': '125',
        'group': '14',
        'name': 'Lead',
        'period': '6',
        'type': 'Metal'},
 'Pd': {'atomic mass': '106.42',
        'atomic number': '46',
        'electrons': '60',
        'group': '10',
        'name': 'Palladium',
        'period': '5',
        'type': 'Transition Metal'},
 'Pm': {'atomic mass': '145',
        'atomic number': '61',
        'electrons': '84',
        'group': '',
        'name': 'Promethium',
        'period': '6',
        'type': 'Lanthanide'},
 'Po': {'atomic mass': '210',
        'atomic number': '84',
        'electrons': '126',
        'group': '16',
        'name': 'Polonium',
        'period': '6',
        'type': 'Metalloid'},
 'Pr': {'atomic mass': '140.908',
        'atomic number': '59',
        'electrons': '82',
        'group': '',
        'name': 'Praseodymium',
        'period': '6',
        'type': 'Lanthanide'},
 'Pt': {'atomic mass': '195.084',
        'atomic number': '78',
        'electrons': '117',
        'group': '10',
        'name': 'Platinum',
        'period': '6',
        'type': 'Transition Metal'},
 'Pu': {'atomic mass': '244',
        'atomic number': '94',
        'electrons': '150',
        'group': '',
        'name': 'Plutonium',
        'period': '7',
        'type': 'Actinide'},
 'Ra': {'atomic mass': '226',
        'atomic number': '88',
        'electrons': '138',
        'group': '2',
        'name': 'Radium',
        'period': '7',
        'type': 'Actinide'},
 'Rb': {'atomic mass': '85.468',
        'atomic number': '37',
        'electrons': '48',
        'group': '1',
        'name': 'Rubidium',
        'period': '5',
        'type': 'Alkali Metal'},
 'Re': {'atomic mass': '186.207',
        'atomic number': '75',
        'electrons': '111',
        'group': '7',
        'name': 'Rhenium',
        'period': '6',
        'type': 'Transition Metal'},
 'Rf': {'atomic mass': '261',
        'atomic number': '104',
        'electrons': '157',
        'group': '4',
        'name': 'Rutherfordium',
        'period': '7',
        'type': 'Transactinide'},
 'Rg ': {'atomic mass': '272',
         'atomic number': '111',
         'electrons': '161',
         'group': '11',
         'name': 'Roentgenium ',
         'period': '7',
         'type': 'Transactinide'},
 'Rh': {'atomic mass': '102.906',
        'atomic number': '45',
        'electrons': '58',
        'group': '9',
        'name': 'Rhodium',
        'period': '5',
        'type': 'Transition Metal'},
 'Rn': {'atomic mass': '222',
        'atomic number': '86',
        'electrons': '136',
        'group': '18',
        'name': 'Radon',
        'period': '6',
        'type': 'Alkali Metal'},
 'Ru': {'atomic mass': '101.07',
        'atomic number': '44',
        'electrons': '57',
        'group': '8',
        'name': 'Ruthenium',
        'period': '5',
        'type': 'Transition Metal'},
 'S': {'atomic mass': '32.065',
       'atomic number': '16',
       'electrons': '16',
       'group': '16',
       'name': 'Sulfur',
       'period': '3',
       'type': 'Nonmetal'},
 'Sb': {'atomic mass': '121.76',
        'atomic number': '51',
        'electrons': '71',
        'group': '15',
        'name': 'Antimony',
        'period': '5',
        'type': 'Metalloid'},
 'Sc': {'atomic mass': '44.956',
        'atomic number': '21',
        'electrons': '24',
        'group': '3',
        'name': 'Scandium',
        'period': '4',
        'type': 'Transition Metal'},
 'Se': {'atomic mass': '78.96',
        'atomic number': '34',
        'electrons': '45',
        'group': '16',
        'name': 'Selenium',
        'period': '4',
        'type': 'Nonmetal'},
 'Sg': {'atomic mass': '266',
        'atomic number': '106',
        'electrons': '160',
        'group': '6',
        'name': 'Seaborgium',
        'period': '7',
        'type': 'Transactinide'},
 'Si': {'atomic mass': '28.086',
        'atomic number': '14',
        'electrons': '14',
        'group': '14',
        'name': 'Silicon',
        'period': '3',
        'type': 'Metalloid'},
 'Sm': {'atomic mass': '150.36',
        'atomic number': '62',
        'electrons': '88',
        'group': '',
        'name': 'Samarium',
        'period': '6',
        'type': 'Lanthanide'},
 'Sn': {'atomic mass': '118.71',
        'atomic number': '50',
        'electrons': '69',
        'group': '14',
        'name': 'Tin',
        'period': '5',
        'type': 'Metal'},
 'Sr': {'atomic mass': '87.62',
        'atomic number': '38',
        'electrons': '50',
        'group': '2',
        'name': 'Strontium',
        'period': '5',
        'type': 'Alkaline Earth Metal'},
 'Ta': {'atomic mass': '180.948',
        'atomic number': '73',
        'electrons': '108',
        'group': '5',
        'name': 'Tantalum',
        'period': '6',
        'type': 'Transition Metal'},
 'Tb': {'atomic mass': '158.925',
        'atomic number': '65',
        'electrons': '94',
        'group': '',
        'name': 'Terbium',
        'period': '6',
        'type': 'Lanthanide'},
 'Tc': {'atomic mass': '98',
        'atomic number': '43',
        'electrons': '55',
        'group': '7',
        'name': 'Technetium',
        'period': '5',
        'type': 'Transition Metal'},
 'Te': {'atomic mass': '127.6',
        'atomic number': '52',
        'electrons': '76',
        'group': '16',
        'name': 'Tellurium',
        'period': '5',
        'type': 'Metalloid'},
 'Th': {'atomic mass': '232.038',
        'atomic number': '90',
        'electrons': '142',
        'group': '',
        'name': 'Thorium',
        'period': '7',
        'type': 'Actinide'},
 'Ti': {'atomic mass': '47.867',
        'atomic number': '22',
        'electrons': '26',
        'group': '4',
        'name': 'Titanium',
        'period': '4',
        'type': 'Transition Metal'},
 'Tl': {'atomic mass': '204.383',
        'atomic number': '81',
        'electrons': '123',
        'group': '13',
        'name': 'Thallium',
        'period': '6',
        'type': 'Metal'},
 'Tm': {'atomic mass': '168.934',
        'atomic number': '69',
        'electrons': '100',
        'group': '',
        'name': 'Thulium',
        'period': '6',
        'type': 'Lanthanide'},
 'Ts': {'atomic mass': '295',
        'atomic number': '117',
        'electrons': '178',
        'group': '17',
        'name': 'Tennessine',
        'period': '7',
        'type': ''},
 'U': {'atomic mass': '238.029',
       'atomic number': '92',
       'electrons': '146',
       'group': '',
       'name': 'Uranium',
       'period': '7',
       'type': 'Actinide'},
 'V': {'atomic mass': '50.942',
       'atomic number': '23',
       'electrons': '28',
       'group': '5',
       'name': 'Vanadium',
       'period': '4',
       'type': 'Transition Metal'},
 'W': {'atomic mass': '183.84',
       'atomic number': '74',
       'electrons': '110',
       'group': '6',
       'name': 'Wolfram',
       'period': '6',
       'type': 'Transition Metal'},
 'Xe': {'atomic mass': '131.293',
        'atomic number': '54',
        'electrons': '77',
        'group': '18',
        'name': 'Xenon',
        'period': '5',
        'type': 'Noble Gas'},
 'Y': {'atomic mass': '88.906',
       'atomic number': '39',
       'electrons': '50',
       'group': '3',
       'name': 'Yttrium',
       'period': '5',
       'type': 'Transition Metal'},
 'Yb': {'atomic mass': '173.054',
        'atomic number': '70',
        'electrons': '103',
        'group': '',
        'name': 'Ytterbium',
        'period': '6',
        'type': 'Lanthanide'},
 'Zn': {'atomic mass': '65.38',
        'atomic number': '30',
        'electrons': '35',
        'group': '12',
        'name': 'Zinc',
        'period': '4',
        'type': 'Transition Metal'},
 'Zr': {'atomic mass': '91.224',
        'atomic number': '40',
        'electrons': '51',
        'group': '4',
        'name': 'Zirconium',
        'period': '5',
        'type': 'Transition Metal'}}